apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: demo
spec:
  template:
    spec:
      containers:
        - image: docker.io/pmbanugo/knative-tekton
          imagePullPolicy: Always
          env:
            - name: TARGET
              value: Testing how this works with Knative.
